services:
  server:
    container_name: server
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./resources:/app/resources

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jira
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 2s
      timeout: 30s
      retries: 10
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - server

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db-data
      o: bind