services:
  server:
    container_name: server
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DEBUG=true
    volumes:
      - server_resources:/app/resources

  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jira
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 2s
      timeout: 30s
      retries: 10
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

volumes:
  server_resources:
  db_data:
  nginx_config: